services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      # Allocate API key from https://console.curseforge.com/
      CF_API_KEY: ${CF_API_KEY}
      # Example of overriding modloader version for a Fabric modpack
      # Refer to https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#api-key
      CF_SLUG: "cobblemon-fabric"
      # Override the mod loader version from the modpack
      CF_MOD_LOADER_VERSION: "0.16.14"
      MEMORY: "4G"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true

# See https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#custom-modloader-versions
