services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: ${CF_API_KEY}
      CF_MODPACK_MANIFEST: /manifests/manifest.json
      CF_SLUG: "custom"
      MEMORY: 2G
    volumes:
      - mc-data:/data
      - ./manifests:/manifests:ro
    ports:
      - "25565:25565"

volumes:
  mc-data: {}
