version: '3.8'

services:
  mc:
#    build: .
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
#      TYPE: SPIGOT
#      VERSION: 1.11.2
      PROXY: proxy:3128
  proxy:
    image: sameersbn/squid

