version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FORGE
      VERSION: 1.15.2
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "true"
    ports:
      - 25565:25565
    volumes:
      - data:/data
      - ./mods.txt:/extras/mods.txt:ro

volumes:
  data:
