version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-8
      CF_FILENAME_MATCHER: "1.0.6"
      CF_DOWNLOADS_REPO: /downloads
      MEMORY: 4G
    volumes:
      - ./data:/data
      - ./downloads:/downloads