name: Validate PR

on:
  pull_request:
    branches: [ master ]
    types: [assigned, opened, synchronize, labeled]

env:
  IMAGE_TO_TEST: itzg/minecraft-server:test-${{ github.repository_owner }}-${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64
          tags: ${{ env.IMAGE_TO_TEST }}
          load: true
          cache-from: type=gha

      - name: Run tests
        run: |
          tests/test.sh

      - name: Gather Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            itzg/minecraft-server

      - name: Push
        if: contains(github.event.pull_request.labels.*.name, 'ci/push-image')
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          pull: true
          push: true
          cache-from: type=gha
          labels: ${{ steps.meta.outputs.labels }}
